config/routes.rb
Rails.application.routes.draw do
  resources :snikks
  devise_for :users
  
  root 'snikks#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/snikk.rb
class Snikk < ApplicationRecord
  belongs_to :user
  
  validates :body, presence: true, length: { maximum: 140 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  has_many :snikks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/snikks_controller.rb
class SnikksController < ApplicationController
  before_action :set_snikk, only: [:show, :edit, :update, :destroy]

  # GET /snikks
  # GET /snikks.json
  def index
    @snikks = Snikk.all.reverse_order
  end

  # GET /snikks/1
  # GET /snikks/1.json
  def show
  end

  # GET /snikks/new
  def new
    @snikk = current_user.snikks.build
  end

  # GET /snikks/1/edit
  def edit
  end

  # POST /snikks
  # POST /snikks.json
  def create
    @snikk = current_user.snikks.create(snikk_params)

    respond_to do |format|
      if @snikk.save
        format.html { redirect_to @snikk, notice: 'Snikk was successfully created.' }
        format.json { render :show, status: :created, location: @snikk }
      else
        format.html { render :new }
        format.json { render json: @snikk.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /snikks/1
  # PATCH/PUT /snikks/1.json
  def update
    respond_to do |format|
      if @snikk.update(snikk_params)
        format.html { redirect_to @snikk, notice: 'Snikk was successfully updated.' }
        format.json { render :show, status: :ok, location: @snikk }
      else
        format.html { render :edit }
        format.json { render json: @snikk.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /snikks/1
  # DELETE /snikks/1.json
  def destroy
    @snikk.destroy
    respond_to do |format|
      format.html { redirect_to snikks_url, notice: 'Snikk was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_snikk
      @snikk = Snikk.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def snikk_params
      params.require(:snikk).permit(:body, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/snikks_helper.rb
module SnikksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Snikksnakk</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Snikksnakk', root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
      </ul>
      <form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <% if(!user_signed_in?) %>
          <li><%= link_to "Sign Up", new_user_registration_path %></li>
          <li><%= link_to "Sign In", new_user_session_path %></li>
        <% else %>
        <li><%= link_to 'New Snikk', new_snikk_path %></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.email %> <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
          </ul>
        </li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/snikks/_form.html.erb
<%= form_with(model: snikk, local: true) do |form| %>
  <% if snikk.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(snikk.errors.count, "error") %> prohibited this snikk from being saved:</h2>

      <ul>
      <% snikk.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <h4>Max 140</h4>
    <%= form.text_area :body, class: "form-control input-lg" %>
  </div>

  <div class="form-group">
    <%= form.submit 'Upload Snikk', class: 'btn btn-success btn-lg' %>
  </div>
<% end %>

app/views/snikks/edit.html.erb
<h1>Editing Snikk</h1>

<%= render 'form', snikk: @snikk %>

<%= link_to 'Show', @snikk %> |
<%= link_to 'Back', snikks_path %>

app/views/snikks/index.html.erb
<p id="notice"><%= notice %></p>

<div class="page-header">
  <h1>Snikk Snakk <small>En plass der du kan snikke</small></h1>
</div>

<center>
<% @snikks.each do |snikk| %>
  <div class="well" style="max-width: 400px">
    <%= snikk.body %>
    <br>
    <%= snikk.user.email %>
  </div>
<% end %>
</center>

app/views/snikks/new.html.erb
<h1>New Snikk</h1>

<%= render 'form', snikk: @snikk %>

<%= link_to 'Back', snikks_path %>

app/views/snikks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Body:</strong>
  <%= @snikk.body %>
</p>

<p>
  <strong>User:</strong>
  <%= @snikk.user %>
</p>

<%= link_to 'Edit', edit_snikk_path(@snikk) %> |
<%= link_to 'Back', snikks_path %>